### ISSUE TITLE
DB issue

### ISSUE THREAD

**Issue by pietrobenito** [CREAT-e/copyright-evidence-api#6]
I've created an empty file for the database and made a config file which points to it but I'm getting an error from sqlite:

`OperationalError: unable to open database file`

Do I need to create the tables manually?

**Comment by Garee** [comment]
The tables _do_ need to be created manually. However, the error message suggests a different issue.

What is in your configuration file? Are you using an absolute path?

**Comment by pietrobenito** [comment]
Yes, you were right. I'm pointing it to an empty file now and it's giving: `OperationalError: no such table: categorylinks`

Is there a schema available for this or should I work it out from the source code?

Many thanks!

**Comment by Garee** [comment]
If you tell me your e-mail address I can send you a copy of the database.

**Comment by pietrobenito** [comment]
It's peter.bennett@glasgow.ac.uk

**Comment by Garee** [comment]
I sent you a download link, let me know if you run into any other issues.

**Comment by pietrobenito** [comment]
Thanks. I'll have a go with it tomorrow.
